### ISSUE TITLE
To-do list (grocery list, gifts list, etc.)

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#8]
Currently I wish uninstalling this app (link below) in order to have one only app that manages all my tasks.

https://f-droid.org/packages/com.thatsmanmeet.taskyapp/

**Comment by vishal2376** [comment]
Right now, the Snaptick app helps you make the best use of your free time.

It doesn't have a to-do list feature yet, but I'm planning to add subtasks in the future. This will make it easier for you to manage your tasks and to-dos.

The main focus of Snaptick will be on managing tasks effectively rather than only on to-dos

**Comment by vishal2376** [comment]
Track issue: #14 Sub-tasks feature
